apiVersion: v1
kind: Namespace
metadata:
  name: myapp-account

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: myapp-account
  name: myapp-account-config-app-name
data:
  APP_NAME: MY ACCOUNT API

---

apiVersion: v1
kind: Secret
metadata:
  namespace: myapp-account
  name: myapp-account-secret-conn-string
stringData:
  CONN_STRING: Server=192.168.0.111\SQL2019;Database=KUBERNETES_MULTI_TENANT_DB_ACCOUNT;Persist Security Info=True;User ID=sa;Password=adminpass;MultipleActiveResultSets=true;Application Name=KUBERNETES_MULTI_TENANT_DB_ACCOUNT;

---


apiVersion: v1
kind: Service
metadata:
  namespace: myapp-account
  name: myapp-account-sqlserver
  labels:
    name: myapp-account-sqlserver
spec:
  ports:
    - port: 1433 
      targetPort: 1433

---

apiVersion: v1
kind: Endpoints
metadata:
  namespace: myapp-account
  name: myapp-account-sqlserver
  labels:
    name: myapp-account-sqlserver
subsets:
  - addresses:
      - ip: 192.168.0.111
    ports:
      - port: 1433

--- 

apiVersion: v1
kind: Service
metadata: 
  namespace: myapp-account
  name: myapp-account-api-service
  labels:
    name: myapp-account-api
spec:
  type: ClusterIP
  selector:
    name: myapp-account-api
  ports:
    - port: 80
      targetPort: 80 

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: myapp-account
  name: myapp-account-api
  labels:
    name: myapp-account-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp-account-api
  template:
    metadata: 
      namespace: myapp-account
      name: myapp-account-api
      labels:
        name: myapp-account-api
    spec:
      containers:
        - name: myapp-account-api
          image: suhutwadiyo/accountapi:1.0
          readinessProbe:
            httpGet:
              path: /WhatsUp
              port: 80
            successThreshold: 3
          ports:
            - containerPort: 80
          envFrom: 
            - configMapRef:
                name: myapp-account-config-app-name
            - secretRef:
                name: myapp-account-secret-conn-string

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  namespace: myapp-account
  name: nginx-ingress
  labels:
    name: nginx-ingress
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec: 
  defaultBackend:
    service:
      name: myapp-account-api-service
      port:
        number: 80
  rules:
    - host: api.account.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp-account-api-service
                port:
                  number: 80

 

