apiVersion: v1
kind: Namespace
metadata:
  name: myapp-tenant02

---   

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: myapp-tenant02
  name: myapp-tenant02-config-app-name
data:
  APP_NAME: MY TENANT02 API

---

apiVersion: v1
kind: Secret
metadata:
  namespace: myapp-tenant02
  name: myapp-tenant02-secret-conn-string
stringData:
  CONN_STRING: Server=192.168.0.105\SQL2019;Database=KUBERNETES_MULTI_TENANT_DB_TENANT02;Persist Security Info=True;User ID=sa;Password=adminpass;MultipleActiveResultSets=true;Application Name=KUBERNETES_MULTI_TENANT_DB_TENANT02;

---

apiVersion: v1
kind: Service
metadata: 
  namespace: myapp-tenant02
  name: myapp-tenant02-api-service
  labels:
    name: myapp-tenant02-api
spec:
  type: ClusterIP
  selector:
    name: myapp-tenant02-api
  ports:
    - port: 80
      targetPort: 80 

---


apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: myapp-tenant02
  name: myapp-tenant02-api
  labels:
    name: myapp-tenant02-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp-tenant02-api
  template:
    metadata: 
      namespace: myapp-tenant02
      name: myapp-tenant02-api
      labels:
        name: myapp-tenant02-api
    spec:
      containers:
        - name: myapp-tenant02-api
          image: suhutwadiyo/tenantapi:1.0
          readinessProbe:
            httpGet:
              path: /WhatsUp
              port: 80
            successThreshold: 3
          ports:
            - containerPort: 80
          envFrom: 
            - configMapRef:
                name: myapp-tenant02-config-app-name
            - secretRef:
                name: myapp-tenant02-secret-conn-string

--- 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  namespace: myapp-tenant02
  name: nginx-ingress
  labels:
    name: nginx-ingress
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec: 
  defaultBackend:
    service:
      name: myapp-tenant02-api-service
      port:
        number: 80
  rules:
    - host: api.tenant02.app.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp-tenant02-api-service
                port:
                  number: 80

 

